site_name: My Docs
site_url: https://github.com/davnish/rasvec

theme:
  name: material
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

plugins:
  - mkdocs-jupyter:
      include_source: true
      execute: false
      ignore_h1_titles: true

nav:
  - Home: index.md
  - Examples: 
    - Vector:
      - examples/create_grid.ipynb
      - examples/clip_vector_by_raster.ipynb
      - examples/rasterization.ipynb
    - Download:
      - examples/downloading.ipynb
    - Raster:
      - examples/patchify_raster.ipynb
      - examples/vectorization.ipynb

