site_name: Rasvec
site_url: https://github.com/davnish/rasvec

theme:
  name: material
  logo: img/rasvec_icon.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Dark mode
      primary: teal
      accent: orange

    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Light mode
      primary: teal
      accent: orange


plugins:
  - mkdocs-jupyter:
      include_source: true
      execute: false
      ignore_h1_titles: true

repo_name: davnish/rasvec
repo_url: https://github.com/davnish/rasvec

nav:
  - Home: index.md
  - Examples: 
    - Vector:
      - examples/create_grid.ipynb
      - examples/clip_vector_by_raster.ipynb
      - examples/rasterization.ipynb
    - Download:
      - examples/downloading.ipynb
    - Raster:
      - examples/patchify_raster.ipynb
      - examples/vectorization.ipynb

copyright: |
  &copy; 2025 <a href="https://github.com/davnish/rasvec.git"  target="_blank" rel="noopener">Nischal Singh</a>